[[redirects]]
  from = '/images/:image'
  to = 'https://ahqwbmhykq.cloudimg.io/v7/_prod_/:image'
  status = 200

[[redirects]]
  from = '/projects'
  to = '/work'
  status = 308

[[redirects]]
  from = '/contact'
  to = '/'
  status = 303

[[headers]]
  for = "/*" # files
  [headers.values]
    Cache-Control = "public, max-age=3600"
