########## OTHER DOMAINS ##########
# alistairshepherd.co.uk
[[redirects]]
  from = 'https://alistairshepherd.co.uk/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# www.alistairshepherd.co.uk
[[redirects]]
  from = 'https://www.alistairshepherd.co.uk/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# alistairshepherd.com
[[redirects]]
  from = 'https://alistairshepherd.com/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# www.alistairshepherd.com
[[redirects]]
  from = 'https://www.alistairshepherd.com/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# accudio.com
[[redirects]]
  from = 'https://accudio.com/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# www.accudio.com
[[redirects]]
  from = 'https://www.accudio.com/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# accudio.co.uk
[[redirects]]
  from = 'https://accudio.co.uk/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# www.accudio.co.uk
[[redirects]]
  from = 'https://www.accudio.co.uk/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# accudiodesign.com
[[redirects]]
  from = 'https://accudiodesign.com/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

# www.accudiodesign.com
[[redirects]]
  from = 'https://www.accudiodesign.com/*'
  to = 'https://alistairshepherd.uk/:splat'
  status = 301
  force = true

########## OLD URLS ##########
[[redirects]]
  from = '/services/*'
  to = '/work'
  status = 301

[[redirects]]
  from = '/portfolio/*'
  to = '/work'
  status = 301

[[redirects]]
  from = '/about/accudio'
  to = '/about'
  status = 301


########## SITE FUNCTIONALITY ##########
[[redirects]]
  from = '/images/:image'
  to = 'https://ahqwbmhykq.cloudimg.io/v7/_prod_/:image'
  status = 200

[[redirects]]
  from = '/projects'
  to = '/work'
  status = 301

[[redirects]]
  from = '/contact'
  to = '/'
  status = 301

[[headers]]
  for = '/*' # all files
  [headers.values]
    Cache-Control = 'public, max-age=3600'
    Content-Security-Policy = "default-src 'self' 'unsafe-inline'; img-src https:; frame-src https:; object-src 'none';"
    Permissions-Policy = 'fullscreen=(), geolocation=(), camera=()'
    Referrer-Policy = 'strict-origin-when-cross-origin'
    Strict-Transport-Security = 'max-age=31536000; preload; includeSubDomains'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'DENY'
    X-Xss-Protection = '1; mode=block'

# Set hashed assets to be immutable
[[headers]]
  for = "*-a1*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*-a1*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

# Other asset caching
[[headers]]
  for = "*.woff2" # fonts
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
[[headers]]
  for = "/fonts/fonts.css" # fonts.css
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
[[headers]]
  for = "/meta/*" # meta files
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"
