[[redirects]]
  from = '/images/:image'
  to = 'https://ahqwbmhykq.cloudimg.io/v7/_prod_/:image'
  status = 200

[[redirects]]
  from = '/projects'
  to = '/work'
  status = 308

[[redirects]]
  from = '/contact'
  to = '/'
  status = 303

[[headers]]
  for = '/' # all files
  [headers.values]
    Cache-Control = 'public, max-age=3600'
    Content-Security-Policy-Report-Only = "default-src 'self'; img-src https:; frame-src https:; object-src 'none'; media-src: 'none';"
    Referrer-Policy = 'strict-origin-when-cross-origin'
    X-Content-Type-Options = 'nosniff'
    X-Frame-Options = 'SAMEORIGIN'
    X-Xss-Protection = '1; mode=block'
